### ISSUE TITLE
Clicking Input Methods crashes Switchboard

### ISSUE THREAD

**Issue by BananaManCJ** [ele-l10n-cjk/switchboard-plug-inputmethod#20]
[error.txt](https://github.com/ele-l10n-cjk/switchboard-plug-inputmethod/files/4792477/error.txt)

**Comment by ryonakano** [comment]
I guess this is because you're not running ibus-daemon. Try to run `ibus-daemon -drx` in your terminal and then open Switchboard again.

**Comment by BananaManCJ** [comment]
Nope, still crashes. It doesn't crash if I run ```sudo io.elementary.switchboard``` but the settings don't do anything because I'm the root user.

**Comment by BananaManCJ** [comment]
It also works as user if I run ```sudo ibus-daemon -drx``` instead of ```ibus-daemon -drx```, but again the settings do nothing.

**Comment by BananaManCJ** [comment]
Figured it out, I added 
```
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
```
to the end of my ~/.profile file and ran ```sudo service lightdm restart``` and it's working now!
